defaults:
  - _self_
  # - model: small
  - override hydra/launcher: submitit_slurm

# added this from small.yaml
model:
  name: small
  type: ddit
  hidden_size: 768
  cond_dim: 128
  length: 1024
  n_blocks: 12
  n_heads: 12
  scale_by_sigma: False # change this
  dropout: 0.1
  ngpus: 1
  tokens: 50257 # changed from 50257 in tinystories case

name: small
type: ddit
hidden_size: 768
cond_dim: 128
length: 1024
n_blocks: 12
n_heads: 12
scale_by_sigma: False # change this 
dropout: 0.1
ngpus: 1
tokens: 50257 # changed from 50257 in tinystories case

training:
  batch_size: 64 # changed from 512
  accum: 4 # changed from 1
  n_iters: 1300001
  snapshot_freq: 10000 # 50000
  log_freq: 50
  eval_freq: 100
  snapshot_freq_for_preemption: 1000 # changed from 10000
  weight: standard
  snapshot_sampling: True
  ema: 0.9999

data:
  train: tinystories # changed from openwebtext
  valid: tinystories # changed from wikitext103
  cache_dir: /scratch3/workspace/avbagchi_umass_edu-data_center/uniform

graph:
  type: absorb # changed from uniform
  file: data
  report_all: False

noise:
  type: loglinear
  sigma_min: 1e-4
  sigma_max: 20

sampling:
  predictor: euler
  steps: 128
  noise_removal: True

eval:
  batch_size: 512
  perplexity: True
  perplexity_batch_size: 1 # changed from 8

optim:
  weight_decay: 0
  optimizer: AdamW
  lr: 3e-4
  beta1: 0.9
  beta2: 0.999
  eps: 1e-8
  warmup: 2500
  grad_clip: 1.


hydra:
  run:
    dir: exp_local/${data.train}/${now:%Y.%m.%d}/${now:%H%M%S}
  sweep:
    dir: exp/${data.train}/${now:%Y.%m.%d}/${now:%H%M%S}
    subdir: ${hydra.job.num}
  launcher:
    max_num_timeout: 100000
    # timeout_min: 10079
    partition: g40x
    account: stanford
    mem_gb: 96
    cpus_per_task: 40
    gpus_per_node: ${ngpus}
    constraint: null

work_dir: '/home/avbagchi_umass_edu/Score-Entropy-Discrete-Diffusion/' # changed
